services:
  prometheus:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/prometheus:v3.13.1
    container_name: prometheus
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--log.level=info'
      - '--log.format=json'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    networks:
      - monitor
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prome_data:/prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  alertmanager:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/alertmanager:v0.32.2
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitor
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=info'
      - '--log.format=json' 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1G'
    volumes:
      - ./alertmanager:/etc/alertmanager:ro
      - alrt_data:/alertmanager
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  prometheus-alert:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/prometheus-alert:v5.0.0
    container_name: prometheus-alert
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitor
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./prometheusalert/conf:/app/conf
      - promalert_data:/app/db
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  victoriametrics:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/victoria-metrics:v1.147.0
    container_name: victoriametrics
    hostname: victoriametrics
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8428:8428"
    networks:
      - monitor
    command:
      - "--loggerTimezone=Asia/Shanghai"
      - "--storageDataPath=/storage"
      - "--retentionPeriod=30d"
    volumes:
      - vm_data:/storage
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  victorialogs:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/victoria-logs:v1.52.0
    container_name: victorialogs
    restart: always
    ports:
      - "9428:9428"
    networks:
      - monitor
    environment:
      - TZ=Asia/Shanghai
    command:
      - '-storageDataPath=/data/victorialogs'
      - '-retentionPeriod=30d'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    volumes:
      - vl_data:/data/victorialogs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  grafana:
    image: registry.cn-hangzhou.aliyuncs.com/privmirror/grafana:12.3.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Asia/Shanghai
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  prome_data:
  alrt_data:
  promalert_data:
  vm_data:
  vl_data:
  grafana_data:
networks:
  monitor:
    driver: bridge
    name: monitor